version: "3.6"
services:
  csp1:
    build: ./filesharing
    ports:
      - "0.0.0.0:8081:8080"
    environment:
      - BOT_URL=http://bot:9999/visit
  bot:
    build: ./bot
    environment:
      - URL_FILESHARING=http://csp1:8080
      - EMAIL_FILESHARING=admin@srdnlen.it
      - PASSWORD_FILESHARING=redacted
